const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const { spawn } = require('node:child_process');
const { existsSync, mkdirSync } = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const python = process.env.PYTHON || (existsSync(path.join(root, '.venv/bin/python')) ? path.join(root, '.venv/bin/python') : 'python3');
const fixture = spawn(python, ['tests/webui_fixture.py'], {cwd:root, stdio:['ignore','pipe','pipe']});
let diagnostics = '';
fixture.stderr.on('data', data=>{diagnostics += data.toString()});
const ready = new Promise((resolve,reject)=>{
 const timer = setTimeout(()=>reject(new Error('Fixture startup timed out. '+diagnostics)),10000);
 let output = '';
 fixture.stdout.on('data', data=>{
   output += data.toString();
   const match = output.match(/READY (http:\/\/127\.0\.0\.1:\d+)/);
   if(match) { clearTimeout(timer); resolve(match[1]); }
 });
 fixture.on('error', error=>{clearTimeout(timer);reject(error)});
 fixture.on('exit', code=>{clearTimeout(timer);reject(new Error('Fixture exited: '+code+' '+diagnostics))});
});
let browser;
process.on('exit', ()=>fixture.kill());
(async () => {
 const url = await ready;
 const executablePath = process.env.CHROMIUM_PATH || (existsSync('/usr/bin/chromium') ? '/usr/bin/chromium' : undefined);
 browser = await chromium.launch({executablePath,headless:true,args:['--no-sandbox']});
 const errors = [];
 const page = await browser.newPage({viewport:{width:1440,height:900}});
 page.on('pageerror', e=>errors.push(e.message));
 page.on('console', m=>{if(m.type()==='error')errors.push(m.text())});
 page.on('dialog', async d=>{assert.equal(d.type(),'beforeunload');await d.accept()});
 await page.goto(url+'/config');
 if (process.env.WEBUI_SCREENSHOTS) {
   mkdirSync(process.env.WEBUI_SCREENSHOTS,{recursive:true});
   await page.screenshot({path:path.join(process.env.WEBUI_SCREENSHOTS,'settings-desktop.png')});
 }
 assert.equal(await page.locator('.save-state').textContent(),'No unsaved changes');
 assert.equal(await page.locator('.settings-panel:visible').count(),1);
 assert.equal(await page.locator('input:invalid').count(),0,'disabled module credentials must not block save');
 await page.getByLabel('Display name',{exact:true}).fill('Studio');
 assert.equal(await page.locator('.save-state').textContent(),'Unsaved changes');
 await page.getByLabel('Display name',{exact:true}).fill('Home');
 assert.equal(await page.locator('.save-state').textContent(),'No unsaved changes');
 await page.locator('.location-coordinates summary').click();
 await page.locator('#location__latitude').fill('40.12345');
 await page.locator('#location__longitude').fill('-111.67890');
 assert.equal(await page.locator('input:invalid').count(),0,'decimal coordinates must be valid');
 await page.getByRole('tab',{name:'General',exact:true}).focus();
 await page.keyboard.press('ArrowRight');
 assert.equal(await page.getByRole('tab',{name:'Module settings',exact:true}).getAttribute('aria-selected'),'true');
 await page.getByLabel('Enable Mealie — Tonight\'s Dinner',{exact:true}).check();
 assert.equal(await page.locator('#hdr-mealie_today').getAttribute('aria-expanded'),'true');
 await page.locator('#modules__settings__mealie_today__base_url').fill('');
 await page.locator('#hdr-mealie_today').click();
 await page.getByRole('tab',{name:'General',exact:true}).click();
 await page.locator('#hardware__after_hours__start-hour').evaluate(el=>{el.value='99'});
 await page.getByRole('button',{name:'Save & restart',exact:true}).click();
 assert.equal(await page.getByRole('tab',{name:'Module settings',exact:true}).getAttribute('aria-selected'),'true');
 assert.equal(await page.locator('#hdr-mealie_today').getAttribute('aria-expanded'),'true');
 assert.equal(await page.evaluate(()=>document.activeElement.id),'modules__settings__mealie_today__base_url');
 await page.locator('#hardware__after_hours__start-hour').evaluate(el=>{el.value='10'});
 await page.getByLabel('Enable Mealie — Tonight\'s Dinner',{exact:true}).uncheck();
 await page.locator('#hardware__spi_hz').evaluate(el=>{el.value='1'});
 await page.getByRole('tab',{name:'Access',exact:true}).click();
 await page.getByRole('button',{name:'Save & restart',exact:true}).click();
 assert.equal(await page.getByRole('tab',{name:'General',exact:true}).getAttribute('aria-selected'),'true');
 assert.equal(await page.locator('.advanced-settings:not(.location-coordinates)').getAttribute('open'),'');
 await page.locator('#hardware__spi_hz').fill('4000000');
 await page.getByRole('tab',{name:'After hours',exact:true}).click();
 const before = await page.locator('#hardware__after_hours__start').inputValue();
 await page.getByRole('tab',{name:'General',exact:true}).click();
 await page.getByLabel('Time Format',{exact:true}).selectOption('24h');
 assert.equal(await page.locator('#hardware__after_hours__start').inputValue(),before,'format changes must preserve stored time');
 await page.getByRole('tab',{name:'After hours',exact:true}).click();
 assert.equal(await page.locator('#hardware__after_hours__start-hour').inputValue(),'22');
 await page.getByRole('tab',{name:'General',exact:true}).click();
 await page.getByLabel('Time Format',{exact:true}).selectOption('12h');
 await page.getByRole('tab',{name:'After hours',exact:true}).click();
 assert.equal(await page.locator('#hardware__after_hours__start-hour').inputValue(),'10');
 assert.equal(await page.getByLabel('Start Time AM or PM').inputValue(),'PM');
 await page.getByLabel('Start Time hours').fill('11');
 assert.equal(await page.locator('#hardware__after_hours__start').inputValue(),'23:00');
 // Immediate photo operations remain separate from form saving.
 await page.getByLabel('Upload after hours photo').setInputFiles({name:'example.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jH1sAAAAASUVORK5CYII=','base64')});
 await page.getByText('Photo uploaded successfully.').waitFor();
 await page.getByRole('button',{name:'Delete photo',exact:true}).click();
 await page.getByText('Photo deleted.',{exact:true}).waitFor();
 await page.getByRole('tab',{name:'Module settings',exact:true}).click();
 await page.locator('#hdr-countdown').click();
 await page.getByRole('button',{name:'+ Add event',exact:true}).click();
 await page.locator('#modules__settings__countdown__events-list .event-row').last().getByLabel('Event name').fill('Launch');
 await page.locator('#modules__settings__countdown__events-list .event-row').last().getByLabel('Event date').fill('2026-12-01');
 await page.locator('#modules__settings__countdown__events-list .event-row').first().getByRole('button',{name:'Remove'}).click();
 assert.equal(await page.getByLabel('Event name').getAttribute('name'),'modules__settings__countdown__events__0__name');
 await page.getByRole('tab',{name:'General',exact:true}).click();
 await page.getByLabel('Display name',{exact:true}).fill('Studio');
 await Promise.all([page.waitForURL(url+'/config'),page.getByRole('button',{name:'Save & restart',exact:true}).click()]);
 await page.getByText('Settings saved. Display service restarting.').waitFor();
 assert.equal(await page.getByLabel('Display name',{exact:true}).inputValue(),'Studio');
 if (process.env.WEBUI_SCREENSHOTS) {
   await page.screenshot({path:path.join(process.env.WEBUI_SCREENSHOTS,'location-desktop.png')});
   await page.setViewportSize({width:390,height:900});
   await page.screenshot({path:path.join(process.env.WEBUI_SCREENSHOTS,'location-phone.png')});
   await page.setViewportSize({width:1440,height:900});
 }
 assert.equal(await page.locator('#hardware__after_hours__start').inputValue(),'23:00');
 let lookups = 0;
 await page.route('**/location/search', async route=>{
   lookups++;
   const query = route.request().postDataJSON().query;
   const body = query === 'Missing place' ? {results:[]} : query === 'Offline place' ? {error:'Location search is unavailable. Please try again.'} : query.startsWith('123 Main') ? {results:[{label:'123 Main Street, Denver, Colorado, United States',latitude:39.75,longitude:-104.98}]} : {
     results:[{label:'Denver, Colorado, United States',latitude:39.7392,longitude:-104.9903},
              {label:'Denver, Iowa, United States',latitude:42.6714,longitude:-92.3374}],
   };
   await route.fulfill({status:query==='Offline place'?502:200,contentType:'application/json',body:JSON.stringify(body)});
 });
 await page.getByLabel('City, state or street address',{exact:true}).fill('Denver, CO');
 assert.equal(lookups,0,'typing must not send address requests');
 await page.getByLabel('City, state or street address',{exact:true}).press('Enter');
 await page.getByRole('button',{name:'Denver, Colorado, United States',exact:true}).waitFor();
 assert.equal(await page.locator('#location__latitude').inputValue(),'40.12345','search must not apply coordinates before selection');
 await page.getByRole('button',{name:'Denver, Colorado, United States',exact:true}).click();
 assert.equal(await page.locator('#location__latitude').inputValue(),'39.7392');
 assert.equal(await page.locator('#location__longitude').inputValue(),'-104.9903');
 assert.equal(await page.getByLabel('Display name',{exact:true}).inputValue(),'Studio');
 if (process.env.WEBUI_SCREENSHOTS) {
   await page.screenshot({path:path.join(process.env.WEBUI_SCREENSHOTS,'location-desktop.png')});
   await page.setViewportSize({width:390,height:900});
   await page.screenshot({path:path.join(process.env.WEBUI_SCREENSHOTS,'location-phone.png')});
   await page.setViewportSize({width:1440,height:900});
 }
 await page.getByRole('button',{name:'Save & restart',exact:true}).click();
 await page.getByText('Settings saved. Display service restarting.').waitFor();
 assert.equal(await page.getByLabel('City, state or street address',{exact:true}).inputValue(),'Denver, Colorado, United States');
 await page.getByLabel('City, state or street address',{exact:true}).fill('Missing place');
 await page.getByRole('button',{name:'Find location',exact:true}).click();
 await page.getByText('No matching locations. Try adding your state, postal code, or country.').waitFor();
 assert.equal(await page.locator('#location__latitude').inputValue(),'39.7392');
 await page.getByLabel('City, state or street address',{exact:true}).fill('Offline place');
 await page.getByRole('button',{name:'Find location',exact:true}).click();
 await page.getByText('Location search is unavailable. Please try again.').waitFor();
 await page.getByRole('tab',{name:'Access',exact:true}).click();
 await page.getByRole('button',{name:'Save & restart',exact:true}).click();
 assert.equal(await page.getByRole('tab',{name:'General',exact:true}).getAttribute('aria-selected'),'true','unselected drafts must not be saved with old coordinates');
 await page.getByLabel('City, state or street address',{exact:true}).fill('123 Main St, Denver, CO');
 await page.getByRole('button',{name:'Find location',exact:true}).click();
 await page.getByRole('button',{name:'123 Main Street, Denver, Colorado, United States',exact:true}).click();
 await page.getByRole('button',{name:'Save & restart',exact:true}).click();
 await page.getByText('Settings saved. Display service restarting.').waitFor();
 assert.equal(await page.getByLabel('City, state or street address',{exact:true}).inputValue(),'123 Main Street, Denver, Colorado, United States');
 assert.equal(await page.locator('#location__longitude').inputValue(),'-104.98');
 await page.getByLabel('City, state or street address',{exact:true}).fill('');
 assert.equal(await page.locator('input:invalid').count(),0,'clearing search keeps current location');
 await page.locator('.location-coordinates summary').click();
 await page.locator('#location__latitude').fill('39.8');
 assert.equal(await page.locator('#location__address').inputValue(),'','manual coordinates must clear the address label');
 await page.getByRole('button',{name:'Save & restart',exact:true}).click();
 await page.getByText('Settings saved. Display service restarting.').waitFor();
 await page.goto(url+'/config#module-countdown');
 assert.equal(await page.locator('#hdr-countdown').getAttribute('aria-expanded'),'true');
 assert.equal(await page.getByLabel('Event name').inputValue(),'Launch');
 // Open/update dialog using a mocked SSE response, never the live updater.
 await page.route('**/update/stream',route=>route.fulfill({status:200,contentType:'text/event-stream',body:'event: uptodate\ndata: latest\n\n'}));
 await page.getByRole('tab',{name:'Software',exact:true}).click();
 await page.getByRole('button',{name:'Update & restart',exact:true}).click();
 await page.getByRole('heading',{name:'Already up to date',exact:true}).waitFor();
 await page.keyboard.press('Tab');
 assert.equal(await page.evaluate(()=>document.activeElement.textContent),'Close');
 await page.keyboard.press('Escape');
 assert.equal(await page.locator('#upd-modal').isVisible(),false);
 assert.equal(await page.evaluate(()=>document.activeElement.textContent.includes('Update & restart')),true);
 // Desktop drag plus buttons and persisted module payload.
 await page.goto(url+'/modules');
 if (process.env.WEBUI_SCREENSHOTS) await page.screenshot({path:path.join(process.env.WEBUI_SCREENSHOTS,'modules-desktop.png')});
 await page.locator('#item-system_status').dragTo(page.locator('#item-clock'));
 assert.equal(await page.locator('#module-list .module-item').first().getAttribute('data-module'),'system_status');
 await page.getByRole('button',{name:'Move Countdown up',exact:true}).click();
 assert.equal(await page.locator('#module-list .module-item').nth(1).getAttribute('data-module'),'countdown');
 await page.getByLabel('Enable Clock',{exact:true}).uncheck();
 assert.equal(await page.locator('#item-clock .position-badge').textContent(),'—');
 assert.equal(await page.locator('[data-enabled-count]').textContent(),'2');
 await page.getByLabel('Enable Clock',{exact:true}).check();
 const order = await page.locator('#module-list .module-item').evaluateAll(items=>items.filter(x=>x.querySelector('input[type=checkbox]').checked).map(x=>x.dataset.module));
 await Promise.all([page.waitForURL(url+'/modules'),page.getByRole('button',{name:'Save & restart',exact:true}).click()]);
 assert.deepEqual(await page.locator('#module-list .module-item').evaluateAll(items=>items.filter(x=>x.querySelector('input[type=checkbox]').checked).map(x=>x.dataset.module)),order);
 await page.goto(url+'/config');
 await page.getByRole('button',{name:'Save & restart',exact:true}).click();
 await page.getByText('Settings saved. Display service restarting.').waitFor();
 await page.goto(url+'/modules');
 assert.deepEqual(await page.locator('#module-list .module-item').evaluateAll(items=>items.filter(x=>x.querySelector('input[type=checkbox]').checked).map(x=>x.dataset.module)),order);
 for(const width of [320,390,768,1024,1440]) {
   await page.setViewportSize({width,height:900});
   for(const path of ['/config','/modules']) {
     await page.goto(url+path);
     assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`${path} at ${width}px overflows`);
   }
 }
 const noScript = await browser.newPage({javaScriptEnabled:false});
 await noScript.goto(url+'/config');
 assert.equal(await noScript.locator('.settings-panel:visible').count(),5,'sections readable without JavaScript');
 await noScript.close();
 const touch = await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true});
 await touch.goto(url+'/modules');
 const touchOrder = await touch.locator('#module-list .module-item').evaluateAll(items=>items.map(x=>x.dataset.module));
 await touch.locator('#module-list .module-item').nth(1).locator('[data-move=up]').tap();
 assert.equal(await touch.locator('#module-list .module-item').first().getAttribute('data-module'),touchOrder[1]);
 assert.equal(await touch.locator('.save-state').textContent(),'Unsaved changes');
 if (process.env.WEBUI_SCREENSHOTS) await touch.screenshot({path:path.join(process.env.WEBUI_SCREENSHOTS,'modules-phone.png')});
 await touch.close();
 await page.getByRole('button',{name:'Move Clock up',exact:true}).click();
 assert.equal(await page.locator('.save-state').textContent(),'Unsaved changes');
 await page.goto(url+'/config');
 await page.getByRole('tab',{name:'Access',exact:true}).click();
 await page.getByLabel('Password',{exact:true}).fill('browser-test');
 await page.getByRole('button',{name:'Show Password',exact:true}).click();
 assert.equal(await page.getByLabel('Password',{exact:true}).getAttribute('type'),'text');
 await page.getByRole('button',{name:'Save & restart',exact:true}).click();
 await page.goto(url+'/login');
 await page.getByRole('heading',{name:'Welcome back.'}).waitFor();
 await page.getByLabel('Password',{exact:true}).fill('wrong');
 await page.getByRole('button',{name:'Sign in',exact:true}).click();
 assert.equal(await page.getByRole('alert').count(),1);
 await page.getByLabel('Password',{exact:true}).fill('browser-test');
 await page.getByRole('button',{name:'Sign in',exact:true}).click();
 await page.getByRole('heading',{name:'Settings',exact:true}).waitFor();
 assert.equal(await page.getByRole('link',{name:'Sign out',exact:true}).isVisible(),true);
 // The simulated provider outage intentionally produces one HTTP 502 diagnostic.
 const expectedOutage = 'Failed to load resource: the server responded with a status of 502 (Bad Gateway)';
 assert.equal(errors.filter(message=>message===expectedOutage).length,1);
 assert.deepEqual(errors.filter(message=>message!==expectedOutage),[],'unexpected browser errors');
 console.log('PASS: city/address search, selection, errors, persistence, manual coordinates, settings tabs, dirty feedback, disabled credentials, hidden validation, 12/24-hour conversion, photos, events, updates, dragging, touch reordering, persistence, login, no-script settings, and 320–1440px layouts');
 await browser.close();
})().catch(e=>{console.error(e);process.exitCode=1}).finally(async()=>{if(browser)await browser.close();fixture.kill()});
